# Pandas - Filtering and Sorting Data

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", delimiter='\t')
chipo.head(4)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

### Step 4. How many products cost more than $10.00?

In [4]:
chipo.item_price = [float(value[1 : -1]) for value in chipo.item_price]

In [5]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.6+ KB

In [6]:
#chipo[(chipo.item_price>=10)].count()
chipo.order_id.where(chipo.item_price>=10).count()

1130

### Step 5. What is the price of each item? 
    ###### print a data frame with only two columns item_name and item_price

In [7]:
chipo[['item_name','item_price']]
#chipo1
#chipo[['item_name','item_price']].groupby('item_name').sum().reset_index()

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [ ]:
### Step 6. Sort by the name of the item

In [8]:
chipo.sort_values(by='item_name', ascending=False)
#chipo[['item_name','item_price']].groupby('item_name').sum().reset_index().sort_values(by='item_name',ascending=True)

,order_id,quantity,item_name,choice_description,item_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
3471,1395,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
...,...,...,...,...,...
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
2374,945,1,6 Pack Soft Drink,[Sprite],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
3600,1443,1,6 Pack Soft Drink,[Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
1279,520,1,6 Pack Soft Drink,[Sprite],6.49
2793,1109,1,6 Pack Soft Drink,[Diet Coke],6.49
1051,432,1,6 Pack Soft Drink,[Coke],6.49
3633,1454,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
879,363,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3693,1480,1,6 Pack Soft Drink,[Diet Coke],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
3766,1508,1,6 Pack Soft Drink,[Coke],6.49
1260,511,1,6 Pack Soft Drink,[Coke],6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3789,1517,1,6 Pack Soft Drink,[Diet Coke],6.49
1392,566,1,6 Pack Soft Drink,[Diet Coke],6.49
3614,1448,1,6 Pack Soft Drink,[Nestea],6.49

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:
chipo.sort_values(by='item_price', ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [10]:
chipo.item_name.where(chipo.item_name=='Veggie Salad Bowl').value_counts()

Veggie Salad Bowl    18
Name: item_name, dtype: int64

### Step 9. How many times people orderd more than one Canned Soda?

In [11]:
chipo.item_name.where((chipo.quantity>=1) & (chipo.item_name=='Canned Soda')).value_counts()

Canned Soda    104
Name: item_name, dtype: int64