# Pandas Exercise: Merging (MPG Cars)

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [4]:
cars1=pd.read_csv("C:\Users\hp\Downloads\python\Pandas Case Study\cars1.csv")
cars2=pd.read_csv("C:\Users\hp\Downloads\python\Pandas Case Study\cars2.csv")

### Step 4. Ops it seems our first dataset has some unnamed blank columns, fix cars1

In [5]:
cars1.drop(['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13'],axis=1,inplace=True)

### Step 5. What is the number of observations in each dataset?

In [13]:
cars1.count()
cars2.count()

mpg             200
cylinders       200
displacement    200
horsepower      200
weight          200
acceleration    200
model           200
origin          200
car             200
dtype: int64

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [10]:
cars1.set_index('mpg')
cars2.set_index('mpg')
cars=pd.merge(cars1,cars2,how='outer')

### Step 7. Ops there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [15]:
cars['owners']=np.random.randint(15000,73000,size=398)

### Step 8. Add the column owners to cars

In [16]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,24180
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,43949
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,47168
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,37529
4,17.0,8,302,140,3449,10.5,70,1,ford torino,58009
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,64271
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,16741
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,66951
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,55095
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,67857
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,41776
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,26341
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,35363
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),31663
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,22097
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,24514
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,61738
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,20926
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,68747
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,34650
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,50096
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,32435
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,63722
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,35669
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,68590
25,10.0,8,360,215,4615,14.0,70,1,ford f250,54228
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,57593
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,44661
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,44025
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,39208
...,...,...,...,...,...,...,...,...,...,...
368,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,54807
369,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,68252
370,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,30679
371,29.0,4,135,84,2525,16.0,82,1,dodge aries se,35836
372,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,47094
373,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,43645
374,23.0,4,151,?,3035,20.5,82,1,amc concord dl,58034
375,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,67888
376,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,56256
377,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,51104
378,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,16789
379,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,25090
380,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,42918
381,36.0,4,107,75,2205,14.5,82,3,honda accord,26434
382,34.0,4,108,70,2245,16.9,82,3,toyota corolla,37741
383,38.0,4,91,67,1965,15.0,82,3,honda civic,60988
384,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),19331
385,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,30069
386,25.0,6,181,110,2945,16.4,82,1,buick century limited,72887
387,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),35374
388,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,25472
389,22.0,6,232,112,2835,14.7,82,1,ford granada l,63780
390,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,56976
391,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,45265
392,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,64952
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,42154
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,40784
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,24542
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,27798
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,55708